#!/bin/sh
## Creates the skeleton of the CA and the private key and the self signed 
## certificate of the CA.

mkdir certs
touch index
touch index.attr
echo "01" > serial
echo "01" > crlnumber

# Create the private key of the CA.
openssl ecparam -out CA.key.pem -name prime256v1 -genkey

# Create the certificate request.
openssl req -new -sha256 -key CA.key.pem -out CA.csr.pem

# Create the self signed certificate.
openssl x509 -req -sha256 -in CA.csr.pem -signkey CA.key.pem -out CA.crt.pem

# Delete the certificate request file, not needed anymore.
rm CA.csr.pem

# Create the initial empty CRL
openssl ca -config CA.conf -gencrl -out CA.crl.pem